import { useShop } from '../../state/useShop';
import { rupiah } from './shopPresentation';
import { packagingContents, packagingValues } from '../../data/productPackaging';

export default function CartReview() {
  const shop = useShop();
  if (!shop.cartReview.issues.length) return null;
  return <section className="cart-review" role="alert" aria-labelledby="cart-review-title"><h2 id="cart-review-title">Periksa kembali keranjang</h2><p>Sesuaikan informasi dan jumlah barang sebelum melanjutkan checkout.</p><ul>{shop.cartReview.issues.map((issue) => <li key={issue.id + issue.type}><strong>{issue.name}</strong>{issue.type === 'stock_error' ? <span>Stok belum dapat diperiksa karena penyimpanan browser tidak tersedia. Coba muat ulang halaman.</span> : issue.type === 'stock' ? <><span>{issue.maximum ? `Stok tidak cukup. Maksimal ${issue.maximum} ${packagingValues(issue.current).packagingType} dengan isi keranjang saat ini.` : 'Stok untuk kemasan ini habis atau sudah digunakan pilihan kemasan lain pada keranjang.'}</span>{issue.maximum > 0 && <button type="button" className="bam-button-secondary" onClick={() => shop.dispatch({ type: 'quantity', id: issue.id, quantity: issue.maximum })}>Sesuaikan jumlah dengan stok</button>}<button type="button" className="bam-button-danger" onClick={() => shop.dispatch({ type: 'remove', id: issue.id })}>Hapus dari keranjang</button></> : issue.type === 'unavailable' ? <><span>Produk sudah tidak tersedia.</span><button type="button" className="bam-button-danger" onClick={() => shop.dispatch({ type: 'remove', id: issue.id })}>Hapus barang tidak tersedia</button></> : <><span>Informasi diperbarui menjadi {issue.current.name} · {rupiah(issue.current.price)} per {packagingValues(issue.current).packagingType}.</span><span>Kemasan terbaru: {packagingContents(issue.current)}.</span></>}</li>)}</ul>{shop.cartReview.issues.some((issue) => issue.type === 'changed') && <button type="button" className="bam-button-secondary" onClick={shop.updateCart}>Gunakan informasi dan harga terbaru</button>}</section>;
}
