import test from 'node:test';
import assert from 'node:assert/strict';
import { Window } from 'happy-dom';
import { createServer } from 'vite';
import { act, createElement } from 'react';
import { createApp } from '../../server/app.js';

test('pembeli: filter dan kembali, validasi checkout, pilihan pembayaran, pembatalan tersimpan, dan harga baru', async () => {
  const api = createApp({ dbPath: ':memory:' }); const seed = JSON.parse(JSON.stringify(api.catalog.snapshot())); api.db.close();
  const server = await createServer({ configFile: false, resolve: { preserveSymlinks: true }, oxc: { jsx: { runtime: 'automatic' } }, optimizeDeps: { noDiscovery: true }, server: { middlewareMode: true, hmr: false, ws: false, watch: null }, appType: 'custom', ssr: { external: ['react', 'react-dom', 'react/jsx-runtime', 'react/jsx-dev-runtime'] } });
  const [{ default: App }, orders] = await Promise.all(['/src/App.jsx', '/src/state/orderModel.js'].map((path) => server.ssrLoadModule(path)));
  const start = '/pemasok/demo-pangan?q=balado&merek=rasa-contoh&urut=low&kategori=snack&sub=keripik';
  const dom = new Window({ url: 'http://localhost/#' + start });
  const previousFetch = globalThis.fetch;
  globalThis.window = dom; globalThis.document = dom.document; globalThis.HTMLElement = dom.HTMLElement;
  globalThis.ResizeObserver = dom.ResizeObserver;
  Object.defineProperty(globalThis, 'navigator', { value: dom.navigator, configurable: true });
  Object.defineProperty(globalThis, 'localStorage', { value: dom.localStorage, configurable: true });
  globalThis.IS_REACT_ACT_ENVIRONMENT = true; dom.scrollTo = () => {};
  dom.HTMLDialogElement.prototype.showModal = function () { this.setAttribute('open', ''); };
  dom.HTMLDialogElement.prototype.close = function () { this.removeAttribute('open'); };
  let delayCatalog = false; let releaseCatalog;
  globalThis.fetch = async (url) => {
    if (url === '/api/catalog') {
      if (delayCatalog) return new Promise((resolve) => { releaseCatalog = () => resolve(new Response(JSON.stringify(seed))); });
      return new Response(JSON.stringify(seed));
    }
    if (url === '/api/auth/me') return new Response('{}', { status: 401 });
    throw new Error('Unexpected request: ' + url);
  };
  const { createRoot } = await import('react-dom/client');
  const container = dom.document.createElement('div'); dom.document.body.append(container); const root = createRoot(container);
  const settle = () => new Promise((resolve) => setTimeout(resolve, 0));
  const click = (element) => act(async () => { assert.ok(element, 'control exists'); element.click(); await settle(); });
  const button = (text) => [...container.querySelectorAll('button')].find((element) => element.textContent === text);
  const fill = (selector, value) => act(async () => {
    const element = container.querySelector(selector); assert.ok(element, selector);
    const prototype = element.tagName === 'TEXTAREA' ? dom.HTMLTextAreaElement.prototype : element.tagName === 'SELECT' ? dom.HTMLSelectElement.prototype : dom.HTMLInputElement.prototype;
    Object.getOwnPropertyDescriptor(prototype, 'value').set.call(element, value);
    element.dispatchEvent(new dom.Event(element.tagName === 'SELECT' ? 'change' : 'input', { bubbles: true })); await settle();
  });
  try {
    await act(async () => { root.render(createElement(App)); await settle(); });
    assert.equal(container.querySelectorAll('.product-card').length, 1);
    assert.match(container.querySelector('#catalog-title').textContent, /balado/);
    await click(button('☰ Semua Kategori'));
    assert.equal(container.querySelector('[role="tab"][aria-selected="true"]').textContent, 'Kategori');
    assert.ok(container.querySelector('.bam-catalog-grid a[href="#/kategori/snack/keripik"]'));
    await click(container.querySelector('[data-view="suppliers"]'));
    assert.match(container.querySelector('.bam-catalog-content').textContent, /Rasa Contoh/);
    await click(button('☰ Semua Kategori'));
    await click(container.querySelector('.product-image'));
    assert.equal(container.querySelector('.detail-packages input[name="product-packaging"]').parentElement.textContent, 'Satuan');
    assert.equal(container.querySelectorAll('.detail-packages input[name="product-packaging"]').length, 1, 'products with no pack/dus prices only offer the actual single-unit SKU');
    assert.equal(container.querySelector('.product-back-link').getAttribute('href'), '#' + start);
    await click(container.querySelector('.product-back-link'));
    assert.equal(dom.location.hash, '#' + start);
    assert.equal(container.querySelector('.catalog-toolbar select').value, 'low');
    assert.equal(container.querySelectorAll('.catalog-filter-chips a').length, 4);
    await click(container.querySelector('.product-image'));
    await click(container.querySelector('input[name="product-size"][value="snack-pedas-23g"]'));
    await click(button('Beli sekarang'));
    assert.match(container.querySelector('h1').textContent, /Keranjang belanja/);
    await click(button('Batalkan belanja')); assert.ok(container.querySelector('dialog[open]'));
    await click(button('Kembali')); assert.equal(container.querySelector('dialog'), null);
    await click(button('Batalkan belanja')); await click(button('Ya, batalkan'));
    assert.equal(dom.location.hash, '#/');
    await click(container.querySelector('a[href="#/keranjang"]'));
    assert.ok(container.querySelector('a[href="#/checkout"]'), 'cancellation keeps the cart by default');
    await click(container.querySelector('a[href="#/checkout"]'));
    await click(button('Batalkan checkout')); await click(button('Kembali'));
    await click(container.querySelector('.checkout-desktop-submit'));
    assert.ok(container.querySelector('#checkout-name[aria-invalid="true"]'));
    assert.equal(orders.readOrders(dom.sessionStorage).length, 0);
    await fill('#checkout-name', 'Pembeli Uji'); await fill('#checkout-address', 'Alamat untuk pengujian frontend');
    const group = (label) => [...container.querySelectorAll('.payment-group-options button')].find((element) => element.textContent.endsWith(label));
    await click(group('Virtual Account')); await click(container.querySelector('input[value="va-mandiri"]'));
    assert.match(container.querySelector('.checkout-selected-payment').textContent, /Mandiri Virtual Account/);
    assert.equal(group('Kartu'), undefined);
    assert.equal(container.querySelector('input[value="card-mastercard"]'), null);
    await click(group('E-wallet'));
    for (const id of ['wallet-dana', 'wallet-gopay', 'wallet-shopeepay', 'wallet-ovo']) assert.ok(container.querySelector(`input[value="${id}"]`));
    await click(container.querySelector('input[value="wallet-ovo"]'));
    delayCatalog = true;
    await click(container.querySelector('.checkout-desktop-submit'));
    assert.equal(container.querySelector('.checkout-desktop-submit').disabled, true);
    await act(async () => container.querySelector('#checkout-form').dispatchEvent(new dom.Event('submit', { bubbles: true, cancelable: true })));
    assert.equal(orders.readOrders(dom.sessionStorage).length, 0);
    await act(async () => {
      const navigation = new Promise((resolve) => dom.addEventListener('hashchange', resolve, { once: true }));
      delayCatalog = false; releaseCatalog(); await navigation;
    });
    const first = orders.readOrders(dom.sessionStorage)[0];
    assert.equal(first.payment.id, 'wallet-ovo'); assert.equal(first.status, 'awaiting_payment');
    assert.match(container.textContent, /Pesanan dibuat, metode pembayaran tercatat/);
    await click(button('Batalkan pesanan'));
    await fill('dialog select', 'Ingin mengganti metode pembayaran');
    await click(button('Ya, batalkan pesanan'));
    assert.match(container.querySelector('h1').textContent, /dibatalkan/);
    assert.equal(orders.readOrder(first.id, dom.sessionStorage).status, 'cancelled');
    await click(container.querySelector('a[href="#/pesanan"]'));
    await click(button('Dibatalkan')); assert.equal(container.querySelectorAll('.orders-card').length, 1);
    await click(container.querySelector('.orders-card a[href^="#/pesanan/"]'));
    assert.match(container.querySelector('h1').textContent, /dibatalkan/);
    assert.equal(button('Batalkan pesanan'), undefined);
    await act(async () => { dom.location.hash = '/produk/snack-pedas-23g'; await settle(); });
    await click(button('Beli sekarang')); await click(container.querySelector('a[href="#/checkout"]'));
    await fill('#checkout-name', 'Pembeli Uji'); await fill('#checkout-address', 'Alamat untuk pengujian frontend');
    const variant = seed.edits.find((item) => item.groupId === 'snack-pedas').variants.find((item) => item.id === 'snack-pedas-23g'); variant.price = '3725';
    await click(container.querySelector('.checkout-desktop-submit'));
    assert.equal(orders.readOrders(dom.sessionStorage).length, 1);
    assert.ok(container.querySelector('.cart-review'));
    assert.equal(container.querySelector('.checkout-desktop-submit').disabled, true);
    await click(button('Gunakan informasi dan harga terbaru'));
    await act(async () => {
      const navigation = new Promise((resolve) => dom.addEventListener('hashchange', resolve, { once: true }));
      container.querySelector('.checkout-desktop-submit').click(); await navigation;
    });
    assert.equal(orders.readOrders(dom.sessionStorage).length, 2);
    assert.equal(orders.readOrders(dom.sessionStorage).find((item) => item.status !== 'cancelled').total, 13725);
    await act(async () => { dom.location.hash = '/produk/snack-pedas-23g'; await settle(); });
    await click(button('Beli sekarang')); await click(button('Batalkan belanja'));
    await click(container.querySelector('dialog input[type="checkbox"]'));
    await click(button('Ya, batalkan'));
    await click(container.querySelector('a[href="#/keranjang"]'));
    assert.equal(container.querySelector('a[href="#/checkout"]'), null, 'empty-cart cancellation removes the checkout action');
    assert.equal(orders.readOrders(dom.sessionStorage).length, 2, 'shopping cancellation keeps order history');
    await act(async () => { dom.location.hash = '/bantuan'; await settle(); });
    assert.match(container.querySelector('h1').textContent, /Pusat bantuan/);
    assert.ok(container.querySelector('footer nav a[href="#/privasi"]'));
    assert.match(container.textContent, /Kontak layanan pelanggan.*belum tersedia/);
  } finally {
    await act(async () => root.unmount()); await server.close(); dom.happyDOM.abort(); globalThis.fetch = previousFetch;
    delete globalThis.window; delete globalThis.document; delete globalThis.localStorage; delete globalThis.HTMLElement; delete globalThis.ResizeObserver; delete globalThis.IS_REACT_ACT_ENVIRONMENT;
  }
});
