import test from 'node:test';
import assert from 'node:assert/strict';
import { Readable } from 'node:stream';
import { Window } from 'happy-dom';
import { createServer } from 'vite';
import { act, createElement } from 'react';
import { createApp } from '../../server/app.js';

test('admin menyimpan pack/dus melalui API; pembeli memilih kombinasi tersedia sampai checkout dan riwayat', async () => {
  const api = createApp({ dbPath: ':memory:' });
  api.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,?)').run('pack-admin', 'Admin Uji', 'pack@test.id', 'Alamat admin uji', 'fixture', '2026-10-09', 'admin');
  // The API uses hashed cookie tokens; a fixture session avoids testing login again.
  const { createHash } = await import('node:crypto');
  const sessionToken = 't'.repeat(43);
  api.db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(createHash('sha256').update(sessionToken).digest('hex'), 'pack-admin', Date.now() + 60000);
  const server = await createServer({ configFile: false, resolve: { preserveSymlinks: true }, oxc: { jsx: { runtime: 'automatic' } }, optimizeDeps: { noDiscovery: true }, server: { middlewareMode: true, hmr: false, ws: false, watch: null }, appType: 'custom', ssr: { external: ['react', 'react-dom', 'react/jsx-runtime', 'react/jsx-dev-runtime'] } });
  const [{ default: App }, orders] = await Promise.all(['/src/App.jsx', '/src/state/orderModel.js'].map((path) => server.ssrLoadModule(path)));
  const dom = new Window({ url: 'http://localhost/#/admin/produk' }); const previousFetch = globalThis.fetch;
  globalThis.window = dom; globalThis.document = dom.document; globalThis.HTMLElement = dom.HTMLElement; globalThis.ResizeObserver = dom.ResizeObserver;
  globalThis.requestAnimationFrame = dom.requestAnimationFrame.bind(dom);
  Object.defineProperty(globalThis, 'navigator', { value: dom.navigator, configurable: true });
  Object.defineProperty(globalThis, 'localStorage', { value: dom.localStorage, configurable: true });
  globalThis.IS_REACT_ACT_ENVIRONMENT = true; dom.scrollTo = () => {}; dom.confirm = () => true;
  globalThis.fetch = async (url, options = {}) => {
    const req = Readable.from(options.body ? [options.body] : []); req.method = options.method || 'GET'; req.url = url;
    req.headers = { host: 'bam.test', origin: 'http://bam.test', cookie: `bam_session=${sessionToken}`, ...options.headers };
    let status; let headers; let body;
    await api.handler(req, { writeHead(s, h) { status = s; headers = h; }, end(value) { body = value; } });
    return new Response(body, { status, headers });
  };
  const { createRoot } = await import('react-dom/client'); const container = dom.document.createElement('div'); dom.document.body.append(container); const root = createRoot(container);
  const settle = () => new Promise((resolve) => setTimeout(resolve, 0));
  const button = (text) => [...container.querySelectorAll('button')].find((element) => element.textContent === text);
  const click = (element) => act(async () => { assert.ok(element, 'control exists'); element.click(); await settle(); });
  const fill = (selector, value) => act(async () => {
    const element = container.querySelector(selector); assert.ok(element, selector);
    const prototype = element.tagName === 'TEXTAREA' ? dom.HTMLTextAreaElement.prototype : element.tagName === 'SELECT' ? dom.HTMLSelectElement.prototype : dom.HTMLInputElement.prototype;
    Object.getOwnPropertyDescriptor(prototype, 'value').set.call(element, value);
    element.dispatchEvent(new dom.Event(element.tagName === 'SELECT' ? 'change' : 'input', { bubbles: true })); await settle();
  });
  const navigate = (route) => act(async () => { const changed = new Promise((resolve) => dom.addEventListener('hashchange', resolve, { once: true })); dom.location.hash = route; await changed; });
  try {
    await act(async () => { root.render(createElement(App)); await settle(); });
    assert.ok(container.querySelector('.admin-table'));
    await click(container.querySelector('button[aria-label="Edit Keripik Singkong Balado ukuran 180g"]'));
    await click(button('+ Tambah varian'));
    await fill('#variant-4-id', 'UI-PACK-180'); await fill('#variant-4-sizeValue', '180'); await fill('#variant-4-price', '90000');
    await fill('#variant-4-packagingType', 'pack');
    assert.equal(container.querySelector('#variant-4-unitsPerPackage').value, '', 'contents must be entered by the admin');
    await click(button('Simpan produk'));
    assert.ok(container.querySelector('#variant-4-unitsPerPackage[aria-invalid="true"]'));
    assert.equal(api.catalog.snapshot().revision, 0);
    await fill('#variant-4-unitsPerPackage', '6');
    await click(button('+ Tambah varian'));
    await fill('#variant-5-id', 'UI-DUS-180'); await fill('#variant-5-sizeValue', '180'); await fill('#variant-5-price', '350000');
    await fill('#variant-5-packagingType', 'dus'); await fill('#variant-5-unitsPerPackage', '24'); await fill('#variant-5-packsPerBox', '4');
    assert.match(container.textContent, /4 pack × 6 satuan = 24 satuan/);
    await click(button('Simpan produk'));
    const saved = api.catalog.snapshot(); assert.equal(saved.revision, 1); assert.equal(container.querySelector('.admin-editor'), null);
    assert.equal(saved.edits.find((draft) => draft.groupId === 'snack-pedas').variants.find((variant) => variant.id === 'UI-PACK-180').unitsPerPackage, '6');
    assert.match(container.querySelector('.admin-table').textContent, /Pack isi 6 satuan/);
    await navigate('/cari?q=balado');
    assert.equal(container.querySelectorAll('.product-card').length, 1, 'all sizes and packages belong to one catalog product');
    await navigate('/produk/snack-pedas');
    assert.equal(container.querySelectorAll('input[name="product-size"]').length, 4, 'size options are deduplicated');
    assert.equal(container.querySelectorAll('input[name="product-packaging"]').length, 3);
    const choices = container.querySelector('.detail-selection');
    assert.equal(choices.querySelectorAll('fieldset').length, 2);
    assert.ok(choices.querySelector('.detail-sizes').compareDocumentPosition(choices.querySelector('.detail-packages')) & dom.Node.DOCUMENT_POSITION_FOLLOWING, 'packaging is directly below size in the same selection section');
    assert.ok(container.querySelector('.shop-breadcrumb').compareDocumentPosition(container.querySelector('.product-back-link')) & dom.Node.DOCUMENT_POSITION_FOLLOWING);
    await click(container.querySelector('input[name="product-packaging"][value="UI-PACK-180"]'));
    assert.match(container.querySelector('.detail-price').textContent, /90.000/);
    assert.equal(container.querySelector('#product-detail-title').textContent, 'Keripik Singkong Balado 180g · 1 pack');
    assert.equal(container.querySelector('.detail-package-price').textContent, 'Harga untuk 1 pack');
    assert.deepEqual([...container.querySelectorAll('input[name="product-packaging"]')].map((input) => input.parentElement.textContent), ['Satuan', 'Pack', 'Dus']);
    assert.doesNotMatch(container.querySelector('.detail-info').textContent, /isi \d+ satuan| = /i);
    await click(container.querySelector('button[aria-label="Tambah jumlah"]'));
    assert.equal(container.querySelector('.detail-package-total').textContent, '2 pack');
    const small = [...container.querySelectorAll('input[name="product-size"]')].find((input) => input.parentElement.textContent === '23g');
    await click(small);
    assert.equal(container.querySelectorAll('input[name="product-packaging"]').length, 1, 'unavailable pack/dus are absent');
    assert.equal(container.querySelector('input[name="product-packaging"]:checked').value, 'snack-pedas-23g');
    assert.equal(container.querySelector('input[name="product-packaging"]').parentElement.textContent, 'Satuan');
    assert.match(container.querySelector('.detail-price').textContent, /3.500/);
    assert.equal(container.querySelector('.detail-quantity output').textContent, '1');
    const large = [...container.querySelectorAll('input[name="product-size"]')].find((input) => input.parentElement.textContent === '180g'); await click(large);
    await click(container.querySelector('input[name="product-packaging"][value="UI-PACK-180"]'));
    await click(container.querySelector('button[aria-label="Tambah jumlah"]')); await click(button('Tambah ke keranjang'));
    await click(container.querySelector('input[name="product-packaging"][value="UI-DUS-180"]'));
    assert.match(container.querySelector('.detail-price').textContent, /350.000/);
    assert.equal(container.querySelector('.detail-package-price').textContent, 'Harga untuk 1 dus');
    await click(button('Beli sekarang'));
    assert.equal(container.querySelectorAll('.cart-item').length, 2);
    assert.equal(container.querySelector('.cart-item .purchase-packaging').textContent, '2 pack');
    assert.doesNotMatch(container.querySelector('.shop-list').textContent, /satuan| = /i);
    assert.match(container.querySelector('.cart-subtotal').textContent, /530.000/);
    await click(container.querySelector('a[href="#/checkout"]'));
    assert.deepEqual([...container.querySelectorAll('.checkout-items .purchase-packaging')].map((entry) => entry.textContent), ['2 pack', '1 dus']);
    assert.doesNotMatch(container.querySelector('.checkout-items').textContent, /satuan| = /i);
    await fill('#checkout-name', 'Pembeli Kemasan'); await fill('#checkout-address', 'Alamat lengkap pengujian kemasan');
    await act(async () => { const changed = new Promise((resolve) => dom.addEventListener('hashchange', resolve, { once: true })); container.querySelector('.checkout-desktop-submit').click(); await changed; });
    const order = orders.readOrders(dom.sessionStorage)[0]; assert.equal(order.total, 540000);
    assert.equal(order.items[0].quantity, 2); assert.equal(order.items[0].details.packaging.unitsPerPackage, 6);
    assert.equal(order.items[1].details.packaging.packsPerBox, 4);
    assert.deepEqual([...container.querySelectorAll('.confirmation-items .purchase-packaging')].map((entry) => entry.textContent), ['2 pack', '1 dus']);
    const changed = api.catalog.snapshot(); changed.edits.find((draft) => draft.groupId === 'snack-pedas').variants.find((variant) => variant.id === 'UI-DUS-180').packsPerBox = '6'; api.catalog.save(changed);
    await navigate('/pesanan');
    assert.deepEqual([...container.querySelectorAll('.orders-products .purchase-packaging')].map((entry) => entry.textContent), ['2 pack', '1 dus']);
    await click(container.querySelector('.orders-card a[href^="#/pesanan/"]'));
    assert.equal(container.querySelectorAll('.confirmation-items .purchase-packaging')[1].textContent, '1 dus');
    assert.equal(orders.readOrder(order.id, dom.sessionStorage).items[1].details.packaging.packsPerBox, 4, 'simpler labels preserve the original order contents');
    assert.equal(orders.readOrder(order.id, dom.sessionStorage).total, 540000);
  } finally {
    await act(async () => root.unmount()); await server.close(); api.db.close(); dom.happyDOM.abort(); globalThis.fetch = previousFetch;
    delete globalThis.window; delete globalThis.document; delete globalThis.localStorage; delete globalThis.HTMLElement; delete globalThis.ResizeObserver; delete globalThis.requestAnimationFrame; delete globalThis.IS_REACT_ACT_ENVIRONMENT;
  }
});
