import test from 'node:test';
import assert from 'node:assert/strict';
import { Window } from 'happy-dom';
import { createServer } from 'vite';
import { act, createElement } from 'react';

test('form admin: navigasi batal mempertahankan isian, setuju menutup form, PT/merek baru tersedia dan SKU baru tidak terkunci', async () => {
  const dom = new Window({ url: 'http://localhost/#/admin' });
  const server = await createServer({ configFile: false, resolve: { preserveSymlinks: true }, oxc: { jsx: { runtime: 'automatic' } }, optimizeDeps: { noDiscovery: true }, server: { middlewareMode: true, hmr: false, ws: false, watch: null }, appType: 'custom', ssr: { external: ['react', 'react-dom', 'react/jsx-runtime', 'react/jsx-dev-runtime'] } });
  const module = await server.ssrLoadModule('/src/pages/AdminPage.jsx').catch(async (error) => { await server.close(); throw error; });
  globalThis.window = dom; globalThis.document = dom.document; Object.defineProperty(globalThis, 'navigator', { value: dom.navigator, configurable: true });
  Object.defineProperty(globalThis, 'localStorage', { value: dom.localStorage, configurable: true });
  globalThis.HTMLElement = dom.HTMLElement; globalThis.IS_REACT_ACT_ENVIRONMENT = true;
  dom.scrollTo = () => {}; let accepted = false; let confirmCount = 0;
  dom.confirm = () => { confirmCount += 1; return accepted; };
  const { createRoot } = await import('react-dom/client');
  const container = dom.document.createElement('div'); dom.document.body.append(container);
  const root = createRoot(container);
  const AdminPage = module.default;
  const render = async (view) => { await act(async () => { root.render(createElement(AdminPage, { view, key: view })); }); };
  const click = async (element) => { assert.ok(element, 'button/link found'); await act(async () => { element.click(); }); };
  const button = (text) => [...container.querySelectorAll('button')].find((entry) => entry.textContent === text);
  const fill = async (selector, value) => {
    const input = container.querySelector(selector); assert.ok(input, selector);
    const prototype = input.tagName === 'SELECT' ? dom.HTMLSelectElement.prototype : dom.HTMLInputElement.prototype;
    await act(async () => { Object.getOwnPropertyDescriptor(prototype, 'value').set.call(input, value); input.dispatchEvent(new dom.Event(input.tagName === 'SELECT' ? 'change' : 'input', { bubbles: true })); });
  };
  try {
    await render('overview'); await click(button('+ Tambah produk')); await fill('#product-baseName', 'Isian belum disimpan');
    await click(container.querySelector('nav a[href="#/admin"]'));
    assert.equal(container.querySelector('#product-baseName').value, 'Isian belum disimpan'); assert.equal(confirmCount, 1);
    accepted = true; await click(container.querySelector('nav a[href="#/admin"]'));
    assert.equal(container.querySelector('.admin-editor'), null);
    await click(button('+ Tambah produk')); assert.equal(container.querySelector('#product-baseName').value, '');
    await click(container.querySelector('nav a[href="#/admin/produk"]')); assert.equal(container.querySelector('.admin-editor'), null);
    await render('suppliers'); await click(button('+ Tambah PT pemasok'));
    await fill('#master-name', 'Isian PT sementara'); accepted = false;
    await click(container.querySelector('nav a[href="#/admin/pemasok"]'));
    assert.equal(container.querySelector('#master-name').value, 'Isian PT sementara');
    accepted = true; await click(container.querySelector('nav a[href="#/admin/pemasok"]'));
    assert.equal(container.querySelector('.admin-master-form'), null); await click(button('+ Tambah PT pemasok'));
    await fill('#master-name', 'PT UI Uji'); await fill('#master-initials', 'UU'); await click(button('Simpan PT pemasok'));
    assert.match(container.textContent, /PT UI Uji/); assert.match(container.textContent, /berhasil disimpan/);
    const masters = await server.ssrLoadModule('/src/data/catalogMasters.js');
    const supplierModule = await server.ssrLoadModule('/src/data/suppliers.js');
    const newSupplier = supplierModule.suppliers.find((entry) => entry.name === 'PT UI Uji');
    await click(container.querySelector(`button[aria-label="Edit ${newSupplier.name}"]`));
    await fill('#master-color', 'rose');
    assert.equal(container.querySelector('.admin-master-sample').style.background, '#fdf2f8');
    await click(button('Simpan PT pemasok'));
    assert.equal(supplierModule.suppliers.find((entry) => entry.id === newSupplier.id).color, 'rose');
    await render('brands'); await click(button('+ Tambah merek')); await fill('#master-name', 'Merek UI Uji');
    const ptCheckbox = [...container.querySelectorAll('fieldset label')].find((label) => label.textContent === 'PT UI Uji').querySelector('input');
    await click(ptCheckbox); await click(button('Simpan merek')); assert.match(container.textContent, /berhasil disimpan/);
    await render('categories'); await click(button('+ Tambah kategori')); await fill('#master-name', 'Kategori UI Uji'); await fill('#master-icon', '💻');
    await fill('#child-0', 'Laptop UI Uji'); await click(button('+ Tambah subkategori')); await fill('#child-1', 'Aksesori UI Uji'); await click(button('Simpan kategori'));
    assert.match(container.textContent, /Aksesori UI Uji/);
    await render('products'); await click(button('+ Tambah produk')); await fill('#product-supplierId', newSupplier.id);
    const options = [...container.querySelector('#product-brandId').options]; assert.ok(options.some((entry) => entry.textContent === 'Merek UI Uji'));
    assert.equal(options.filter((entry) => entry.value).length, 1);
    const brand = masters.brands.find((entry) => entry.name === 'Merek UI Uji'); await fill('#product-brandId', brand.id);
    assert.match(container.querySelector('.admin-form-preview').textContent, /Merek UI Uji/);
    const categoryModule = await server.ssrLoadModule('/src/data/catalog.js'); const category = categoryModule.categories.find((entry) => entry.name === 'Kategori UI Uji');
    await fill('#product-categoryId', category.id); assert.equal(container.querySelector('#product-subcategoryId').options.length, 3);
    const transfer = new dom.DataTransfer(); transfer.items.add(new dom.File(['invalid photo'], 'test.txt', { type: 'text/plain' }));
    const photoInput = container.querySelector('input[type="file"]');
    await act(async () => { photoInput.files = transfer.files; photoInput.dispatchEvent(new dom.Event('change', { bubbles: true })); });
    assert.match(container.textContent, /Pilih JPG, PNG, atau WebP/);
    await click(button('Batal'));
    await click(container.querySelector('button[aria-label="Edit Keripik Singkong Balado ukuran 180g"]'));
    await click(button('+ Tambah varian')); await fill('#variant-4-id', 'snack-pedas');
    assert.equal(container.querySelector('#variant-4-id').readOnly, false);
    await fill('#variant-4-id', 'SKU-UI-BARU'); assert.equal(container.querySelector('#variant-4-id').value, 'SKU-UI-BARU');
    assert.equal(container.querySelector('#variant-0-id').readOnly, true);
    await click(button('Batal'));
    await render('suppliers');
    const usedDelete = container.querySelector('button[aria-label="Hapus PT pemasok PT Pangan Contoh"]');
    assert.equal(usedDelete.disabled, true); assert.match(container.textContent, /Belum dapat dihapus/);
    assert.equal(container.querySelector('button[aria-label="Hapus PT pemasok PT UI Uji"]').disabled, true);
    await render('brands');
    const deleteBrand = container.querySelector('button[aria-label="Hapus merek Merek UI Uji"]'); assert.equal(deleteBrand.disabled, false);
    accepted = false; await click(deleteBrand); assert.ok(masters.brands.some((entry) => entry.id === brand.id));
    accepted = true; await click(deleteBrand); assert.ok(!masters.brands.some((entry) => entry.id === brand.id));
    await render('suppliers'); await click(container.querySelector('button[aria-label="Hapus PT pemasok PT UI Uji"]'));
    assert.ok(!supplierModule.suppliers.some((entry) => entry.id === newSupplier.id));
    await render('categories'); await click(container.querySelector('button[aria-label="Hapus kategori Kategori UI Uji"]'));
    assert.ok(!categoryModule.categories.some((entry) => entry.id === category.id));
  } finally { await act(async () => root.unmount()); await server.close(); dom.happyDOM.abort(); }
});
